### ISSUE TITLE
GUI layout editor?

### ISSUE THREAD

**Issue by darkhog** [Martenfur/TabletFriend#48]
Would be nice if you could make layout visually instead of editing config files.

**Comment by Martenfur** [comment]
Way too much work, never gonna happen. Text editor is more than good enough.

**Comment by darkhog** [comment]
Not for the target audience that despise coding of any kind and just likes to click stuff, a.k.a. The Artists™  
     
      
       
        Dnia 21 czerwca 2024 12:58 minkberry ***@***.***&gt; napisał(a):
       
    
       
         
 Way too much work, never gonna happen. Text editor is more than good enough.

**Comment by Martenfur** [comment]
There's one thing you got wrong - my primary target audience is myself. :)

The problem with GUI editing is that in order to make it - and make it good - you'd have to spend as much time if not more as for the rest of the program. It's a lot, and I mean A LOT of work, and this is just a fun side project for me. The current solution is good and very fast to work with, if you spend half an hour learning the layout structure, which is not that complex, GUI will not make it that much better. More approachable, yes, but as I said I wrote this mainly for myself and put it up for whoever wants to use it also.
